Repository CredisaseZw/rentsafe, pull requests merged in 2025-05, with the labels that each got.

#71 Update CurrencyRate endpoint to currency_rate; add CurrencyViewSet with proper serializer
  accounting/urls.py
  accounting/views.py
Labels: Currency-setup

#87 change 'Adjust' lease action to just 'Lease'
  react-app/src/pages/Leases/Index.jsx
Labels: UI/UX

#86 complete integration of count-safe invoicing with backend
  pnpm-lock.yaml
  react-app/src/components/Client/CreditNoteForm.jsx
  react-app/src/components/Client/InvoiceFormRow.jsx
  react-app/src/components/Client/ProformaInvoicingInvoiceTab.jsx
  react-app/src/components/Client/RecurringInvoicingInvoiceTab.jsx
  react-app/src/components/Client/SalesInvoiceForm.jsx
  react-app/src/components/Client/SalesInvoicingInvoiceTab.jsx
  react-app/src/components/modals/CashSalesModal.jsx
  react-app/src/hooks/component-hooks/useCreditNoteForm.js
  react-app/src/hooks/component-hooks/useInvoiceFormRow.js
  react-app/src/hooks/component-hooks/useProformaInvoiceTab.js
  react-app/src/hooks/component-hooks/useRecurringInvoicingInvoiceTab.js
  react-app/src/hooks/component-hooks/useSalesInvoiceForm.js
  react-app/src/hooks/component-hooks/useSalesInvoicingInvoiceTab.js
  react-app/src/hooks/data/useSalesInvoiceList.js
  react-app/src/hooks/general-hooks/useCurrencies.js
  react-app/src/hooks/modal-hooks/useCashSalesModal.js
  react-app/src/hooks/page-hooks/useProductsAndServices.js
  react-app/src/hooks/page-hooks/useSalesInvoicing.js
  react-app/src/pages/Client/Accounting/Sales/ProductsAndServices.jsx
  react-app/src/pages/Client/Accounting/Sales/SalesInvoicing.jsx
Labels: Invoicing-module, accounts-module
